# -*- coding: utf-8 -*-
"""assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C0MfNKskExnOvg8oOdU-DeMs9OEfHpkm
"""

import csv
import json
import psycopg2

def read_phone_book(file_path, file_type):
    phone_book = []

    if file_type.lower() == 'csv':
        with open(file_path, 'r') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                phone_book.append({
                    'Name': row['first_name'],
                    'Email': row['email'],
                    'Phone_1': row['phone1'],
                    'Phone_2': row['phone']
                })

    elif file_type.lower() == 'json':
        with open(file_path, 'r') as jsonfile:
            data = json.load(jsonfile)
            phone_book = data['phone_book']

    return phone_book

class PhoneBookSQLParser:
    def __init__(self, phone_book, database_connection):
        self.phone_book = phone_book
        self.connection = database_connection
        self.cursor = self.connection.cursor()

        # Create a table in PostgreSQL to store phone book records
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS phone_book (
                Name TEXT,
                Email TEXT,
                Phone_1 TEXT,
                Phone_2 TEXT
            )
        ''')

        # Insert phone book records into the PostgreSQL table
        for record in self.phone_book:
            self.cursor.execute('''
                INSERT INTO phone_book (Name, Email, Phone_1, Phone_2)
                VALUES (%s, %s, %s, %s)
            ''', (record['Name'], record['Email'], record['Phone_1'], record['Phone_2']))

        # Commit the changes
        self.connection.commit()

    def execute_query(self, query):
        self.cursor.execute(query)
        result = self.cursor.fetchall()
        return result

# Example usage:
csv_phone_book = read_phone_book(r"C:\Users\CHETHU\Downloads\50-contacts.csv", 'csv')

# Replace 'your_username', 'your_password', 'your_database', and 'your_host' with your actual credentials
conn = psycopg2.connect(dbname='phone_book', user='postgres', password='Chethu@1999', host='localhost', port='5432')

phone_book_parser = PhoneBookSQLParser(csv_phone_book, conn)

# Example CRUD operations
query = "SELECT * FROM phone_book"
result = phone_book_parser.execute_query(query)
print("\nSQL-like Query Result:")
print(result)